// Customer Journey Problem Catalog + Feature Signal Catalog
// Derived from "Customer Journey Problem Discovery Framework" by Hani Ahmad.
// The orchestrator demo uses 7 problems (F32, F33, F41, F43, F45, F46, F51)
// out of the larger catalog below. This data backs the Journey Map tab so
// product managers can see what's implemented and what's available to plug in.

window.JOURNEY_STAGES = [
  {
    code: 'F1', name: 'Discover', tagline: 'What should I look at?',
    desc: 'The customer arrives without a specific item in mind. They need direction.',
    problems: [
      { code: 'F11', label: 'F1.1 Category Overwhelm',
        voice: '"There are 12,000 jackets — where do I even start?"',
        signals: 'long scroll without filter · broad search query · short session before exit',
        tractability: 'recs-solvable' },
      { code: 'F12', label: 'F1.2 Inspiration Gap',
        voice: '"I don\'t know what\'s in style this season."',
        signals: 'editorial / trend page visits · seasonal search terms',
        tractability: 'recs-assisted' },
      { code: 'F13', label: 'F1.3 Need Translation',
        voice: '"I want something for the rain, but I don\'t know what that\'s called."',
        signals: 'natural-language search · zero-result queries · category bouncing',
        tractability: 'recs-assisted' },
    ],
  },
  {
    code: 'F2', name: 'Explore', tagline: "What's out there?",
    desc: 'Customer is browsing breadth. Wants to see range, find candidates.',
    problems: [
      { code: 'F21', label: 'F2.1 Option Set Stagnation',
        voice: '"I keep seeing the exact same items every time I come back. Is there nothing new?"',
        signals: 'multi-session same-item exposure · low ctr on repeat impressions',
        tractability: 'recs-solvable' },
      { code: 'F22', label: 'F2.2 Filter Friction',
        voice: '"I can\'t refine to what I actually want."',
        signals: 'multiple filter toggles · filter reset · empty result count',
        tractability: 'ux-primary' },
      { code: 'F23', label: 'F2.3 Discovery Boredom',
        voice: '"Nothing surprises me."',
        signals: 'low scroll velocity · short dwell on results · early exit',
        tractability: 'recs-assisted' },
    ],
  },
  {
    code: 'F3', name: 'Narrow', tagline: 'Is this the one?',
    desc: 'Customer has zoomed in on a few items. Now scrutinizing details.',
    problems: [
      { code: 'F31', label: 'F3.1 Detail Anxiety',
        voice: '"I need to see this from every angle before I trust it."',
        signals: 'image zoom · gallery cycles · video play',
        tractability: 'ux-primary' },
      { code: 'F32', label: 'F3.2 Size Anxiety', active: true,
        voice: '"Will this actually fit me?"',
        signals: 'size chart opens · low size confidence · personal return history',
        tractability: 'recs-assisted' },
      { code: 'F33', label: 'F3.3 Quality Signal Deficit', active: true,
        voice: '"This is expensive. Is it actually worth it?"',
        signals: 'image zoom · premium price band · brand searches',
        tractability: 'recs-assisted' },
      { code: 'F34', label: 'F3.4 Style Match Anxiety',
        voice: '"Is this even me? Will I actually wear it?"',
        signals: 'style stretch · wishlist save without cart · revisits',
        tractability: 'recs-assisted' },
      { code: 'F35', label: 'F3.5 PDP Stagnation',
        voice: '"Why are the recommendations on this page the same as yesterday?"',
        signals: 'repeat PDP visit · same module exposure',
        tractability: 'recs-solvable' },
    ],
  },
  {
    code: 'F4', name: 'Evaluate', tagline: 'Which of these 3?',
    desc: 'Customer has a shortlist. Comparing candidates against each other.',
    problems: [
      { code: 'F41', label: 'F4.1 Comparison Friction', active: true,
        voice: '"I have 4 tabs open and I keep flipping between them. I can\'t remember which had better reviews."',
        signals: 'tab switching · revisits · price dwell',
        tractability: 'recs-assisted' },
      { code: 'F42', label: 'F4.2 Social Proof Gap',
        voice: '"3 reviews vs 200 on the other — I can\'t trust this one."',
        signals: 'reviews tab opens · scroll to reviews · low review count item',
        tractability: 'recs-solvable' },
      { code: 'F43', label: 'F4.3 Outfit Visualization', active: true,
        voice: '"What shoes go with this? How does it actually wear?"',
        signals: 'style stretch · mobile device · time on hero image',
        tractability: 'recs-assisted' },
      { code: 'F44', label: 'F4.4 Peer Validation Need',
        voice: '"I wish someone would just tell me which one to get."',
        signals: 'review reading depth · expert-pick clicks · share button',
        tractability: 'recs-assisted' },
      { code: 'F45', label: 'F4.5 Price-Quality Confusion', active: true,
        voice: '"These look identical but one is €60 more. Why?"',
        signals: 'price dwell · price sensitivity · cross-tab price compare',
        tractability: 'recs-assisted' },
      { code: 'F46', label: 'F4.6 Return Hesitation', active: true,
        voice: '"If I pick wrong, returning is a hassle. I\'ll just skip it."',
        signals: 'return policy views · personal return history',
        tractability: 'recs-assisted' },
    ],
  },
  {
    code: 'F5', name: 'Commit', tagline: 'Should I actually buy this?',
    desc: 'Customer is at the threshold. Final commit-or-bail moment.',
    problems: [
      { code: 'F51', label: 'F5.1 Decision Paralysis', active: true,
        voice: '"I\'ve been adding and removing this for an hour. I just can\'t pull the trigger."',
        signals: 'cart oscillation · wishlist depth · revisits',
        tractability: 'recs-assisted' },
      { code: 'F52', label: 'F5.2 Checkout Doubt',
        voice: '"Wait — is this site legit? Is my card safe?"',
        signals: 'guest checkout · trust badge dwell · abandon at payment',
        tractability: 'ux-primary' },
      { code: 'F53', label: 'F5.3 Price Anchoring Block',
        voice: '"I saw this for less last week. I\'ll wait for a sale."',
        signals: 'price history view · long wishlist tenure · sale-page visits',
        tractability: 'recs-assisted' },
    ],
  },
  {
    code: 'F6', name: 'Post-purchase', tagline: 'Now what?',
    desc: 'The item arrived. The next decision starts here.',
    problems: [
      { code: 'F61', label: 'F6.1 Styling Orphan',
        voice: '"I bought this bold jacket and it\'s been sitting because I don\'t know what to wear with it."',
        signals: 'order history · low repeat-wear inference · post-purchase email open',
        tractability: 'recs-assisted' },
      { code: 'F62', label: 'F6.2 Care Knowledge Gap',
        voice: '"How do I wash this without ruining it?"',
        signals: 'care-instructions search · review mentions of damage',
        tractability: 'recs-assisted' },
      { code: 'F63', label: 'F6.3 Wardrobe Drift',
        voice: '"My style has changed. Why are you still showing me the old me?"',
        signals: 'category mix shift · returned items pattern · new search vocab',
        tractability: 'recs-solvable' },
      { code: 'F64', label: 'F6.4 Repeat Trigger',
        voice: '"I love it, want another in a different color."',
        signals: 'past-purchase reorder · color variant views · brand loyalty',
        tractability: 'recs-solvable' },
    ],
  },
];

// Signal feature catalog: 14 active + ~10 available-but-not-implemented.
// Active signals are the same set the orchestrator uses today (in SIGNALS),
// listed here in a richer format for the catalog view.
window.SIGNAL_CATALOG = [
  // Active — Customer profile
  { id: 'size_conf',     name: 'Size Confidence',          group: 'profile',  active: true,
    desc: 'Confidence the customer has in the platform\'s sizing for them.',
    derivedFrom: 'historical return reason codes · size-chart usage' },
  { id: 'price_sens',    name: 'Price Sensitivity',         group: 'profile',  active: true,
    desc: 'How much the customer reacts to price changes and discounts.',
    derivedFrom: 'discount basket share · sale-page visit frequency' },
  { id: 'return_hist',   name: 'Return History',            group: 'profile',  active: true,
    desc: 'Personal historical return rate.',
    derivedFrom: 'orders / returns over last 12 months' },
  { id: 'style_stretch', name: 'Style Stretch',             group: 'profile',  active: true,
    desc: 'How far this item is from the customer\'s typical style.',
    derivedFrom: 'embedding distance to historical wardrobe' },
  { id: 'new',           name: 'New Customer',              group: 'profile',  active: true,
    desc: 'First-time or low-order-count visitor.',
    derivedFrom: 'account age · order count' },
  { id: 'mobile',        name: 'Mobile Device',             group: 'profile',  active: true,
    desc: 'On a phone — narrower screens, fewer tabs, tighter attention.',
    derivedFrom: 'user-agent · viewport size' },

  // Active — Session
  { id: 'size_chart',    name: 'Size Chart Engagement',     group: 'session',  active: true,
    desc: 'How much the customer interacted with sizing tools in this session.',
    derivedFrom: 'size-chart opens · size-finder usage' },
  { id: 'tab_switch',    name: 'Tab Switching',             group: 'session',  active: true,
    desc: 'Rapid back-and-forth between similar PDPs.',
    derivedFrom: 'PDP navigation count · time between switches' },
  { id: 'zoom',          name: 'Image Zoom',                group: 'session',  active: true,
    desc: 'Detailed inspection of the product visuals.',
    derivedFrom: 'zoom events · gallery cycles' },
  { id: 'price_dwell',   name: 'Price Dwell',               group: 'session',  active: true,
    desc: 'Time spent reading the price area.',
    derivedFrom: 'price-block dwell · price-element scroll-to' },
  { id: 'cart_osc',      name: 'Cart Add / Remove',         group: 'session',  active: true,
    desc: 'Cart oscillation — the classic indecision signal.',
    derivedFrom: 'add/remove events on the same item' },
  { id: 'wishlist',      name: 'Wishlist Depth',            group: 'session',  active: true,
    desc: 'How many items are sitting in their wishlist.',
    derivedFrom: 'wishlist size · save velocity' },
  { id: 'return_view',   name: 'Return Policy Views',       group: 'session',  active: true,
    desc: 'Read-throughs of the return policy.',
    derivedFrom: 'returns-page visits · returns-section dwell' },
  { id: 'revisit',       name: 'Revisits to Product',       group: 'session',  active: true,
    desc: 'Coming back to the same PDP across sessions.',
    derivedFrom: 'PDP visit count over 7 days' },

  // Active — Product
  { id: 'price_norm',    name: 'Price Premium-ness',        group: 'product',  active: true,
    desc: 'Where the item sits in the category\'s price distribution.',
    derivedFrom: 'price percentile within category' },

  // Available — not yet wired into a problem detector
  { id: 'search_query',  name: 'Search Vocabulary',         group: 'session',  active: false,
    desc: 'Words the customer is typing — proxy for explicit intent.',
    derivedFrom: 'search keywords · zero-result queries' },
  { id: 'review_scroll', name: 'Reviews Engagement',        group: 'session',  active: false,
    desc: 'How deeply they\'re reading reviews — proxy for social-proof need.',
    derivedFrom: 'reviews-tab dwell · scroll depth · helpful clicks' },
  { id: 'filter_use',    name: 'Filter Activity',           group: 'session',  active: false,
    desc: 'How aggressively the customer is refining results.',
    derivedFrom: 'filter toggles · filter reset · facet count' },
  { id: 'gallery_depth', name: 'Image Gallery Cycles',      group: 'session',  active: false,
    desc: 'Going through multiple product images.',
    derivedFrom: 'gallery next/prev clicks · video plays' },
  { id: 'occasion_kw',   name: 'Occasion Keywords',         group: 'session',  active: false,
    desc: 'Searching wedding, prom, work, vacation — mission flagging.',
    derivedFrom: 'keyword match against occasion lexicon' },
  { id: 'gift_signal',   name: 'Gift Intent',               group: 'session',  active: false,
    desc: 'Buying for someone else, not themselves.',
    derivedFrom: 'gift-wrap toggle · cross-gender browsing · category shift' },
  { id: 'embedding_dist',name: 'Wardrobe Embedding Drift',  group: 'profile', active: false,
    desc: 'How much the customer\'s recent purchases diverge from their historical taste.',
    derivedFrom: 'cosine drift across rolling 90-day basket embeddings' },
  { id: 'season_match',  name: 'Seasonal Fit',              group: 'product', active: false,
    desc: 'How well this item fits the current season for the customer\'s region.',
    derivedFrom: 'season tag · weather data · region' },
  { id: 'inventory_low', name: 'Inventory Pressure',        group: 'product', active: false,
    desc: 'Stock dwindling — urgency cue.',
    derivedFrom: 'units remaining · velocity' },
  { id: 'social_velocity', name: 'Social Velocity',          group: 'product', active: false,
    desc: 'How fast the item is being added to bags / wishlists right now.',
    derivedFrom: 'add-to-bag rate · wishlist rate · trending feed' },
];

// Business-perspective and Shopping-mission lenses — kept brief, displayed
// in the side panels of the Journey Map for context.
window.BUSINESS_LENSES = [
  { code: 'B1', name: 'Revenue / Conversion', desc: 'Direct GMV impact.' },
  { code: 'B2', name: 'Margin Health',        desc: 'Returns cost, basket margin.' },
  { code: 'B3', name: 'Customer Lifetime Value', desc: 'Long-term retention and frequency.' },
  { code: 'B4', name: 'Inventory Health',     desc: 'Move what needs moving.' },
  { code: 'B5', name: 'Brand & Trust',        desc: 'Long-term perception, NPS, advocacy.' },
];

window.MISSIONS = [
  { code: 'M1', name: 'Solve a Need',         desc: '"I need a winter coat."' },
  { code: 'M2', name: 'Replenishment',        desc: '"Same socks, new pack."' },
  { code: 'M3', name: 'Gift Shopping',        desc: '"It\'s for my husband."' },
  { code: 'M4', name: 'Occasion / Event',     desc: '"Black-tie wedding next week."' },
  { code: 'M5', name: 'Outfit / Functional Build', desc: '"Build a hiking kit under €100."' },
  { code: 'M6', name: 'Lifestyle Exploration', desc: '"I\'m getting into running."' },
  { code: 'M7', name: 'Browsing / Window',    desc: '"Just killing time."' },
];
